services:
  - type: web
    name: tennsational
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /admin
        destination: /index.html
      - type: rewrite
        source: /admin/*
        destination: /index.html
      - type: rewrite
        source: /*
        destination: /index.html

