services:
  - type: web
    name: tennsational-restaurant-directory
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: SESSION_SECRET
        generateValue: true
    disk:
      name: tennsational-data
      mountPath: /opt/render/project/src
      sizeGB: 1
